name: Auto Check-in

on:
  schedule:
    # 測試用：每分鐘執行一次（僅用於測試）
    # - cron: "* * * * *"
    # 台灣時間 08:45 上班打卡（UTC 00:45）
    - cron: "45 0 * * 1-5"
    # 台灣時間 12:00 午休下班（UTC 04:00）
    - cron: "0 4 * * 1-5"
    # 台灣時間 13:00 午休上班（UTC 05:00）
    - cron: "0 5 * * 1-5"
    # 台灣時間 17:46 下班打卡（UTC 09:46）
    - cron: "46 9 * * 1-5"
  workflow_dispatch: # 手動觸發

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run auto check-in
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          AUTO_CHECKIN_ENABLED: ${{ secrets.AUTO_CHECKIN_ENABLED }}
          SKIP_DATES: ${{ secrets.SKIP_DATES }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python main.py
